check the available platform to not necessary mention the platform op…
snipsco/teleport pull request #36
Opened 2017-02-05 22:01 UTC by Ledoux

…tion for deploy

@franblas 
here I polished some little things
- it is not anymore necessary to write `tpt -d --platform kubernetes` if there is only teleport-snips as platform
- replace prefixes are a bit smarter : __ if we want just to copy one time the file with the placeholders value, or _type_ if we want to copy them so many as there are different types

2017-02-06 13:23 UTC, franblas requested changes
@Ledoux Please have a look, made a comment and a suggestion, WDYT ?

2017-02-06 13:23 UTC, franblas commented on src/methods/exec.js
> +      platform !== 'teleport-snips'
I would also keep `kubernetes` into the condition. 
`if ( platformScriptNames.includes(script) && platform && (platform !== 'kubernetes' || platform !== 'teleport-snips') )`

2017-02-06 18:36 UTC, franblas approved these changes

2017-02-07 09:36 UTC, Ledoux commented
@franblas allez let's merge :), tx.

2017-02-07 09:36 UTC, merged